language: ruby
bundler_args: --without kitchen_common kitchen_vagrant
rvm:
  - 2.1.8
script:
  - bundle exec rubocop
  - bundle exec foodcritic -f any .
  - bundle exec rspec --color --format progress
